[package]
name = "Tetanus"
version = "0.0.1"
authors = ["LogoiLab <LogoiLab@github.com>"]

[dependencies]
base64 = "0.1.1"
http = "0.0.0-prealpha"
num = "0.1.32"
regex = "0.1.69"
serde = "0.7.5"
serde_json = "0.7.0"
tempdir = "0.3.4"
